#controllers:
    #resource:
    #    path: ../src/Controller/
    #    namespace: App\Controller
    #type: attribute
api_login:
    path: /auth
    methods: ['POST']
api_user_create:
    path: /users
    controller: App\Controller\UserController::create
    methods: ['POST']
api_user_get:
    path: /user
    controller: App\Controller\UserController::get
    methods: ['GET']
